FROM alpine:3.21
WORKDIR /app
RUN apk add --no-cache bash wget
RUN wget -O migrate.tar.gz https://github.com/golang-migrate/migrate/releases/latest/download/migrate.linux-amd64.tar.gz
RUN tar -xzf migrate.tar.gz -C /app && rm migrate.tar.gz
COPY app.env .
COPY db/migration ./db/migration
COPY migrate.sh .
RUN chmod +x /app/migrate.sh
ENTRYPOINT ["/app/migrate.sh"]